/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.geolite.projects.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProjectCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7064955089385507609L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProjectCreatedEvent\",\"namespace\":\"com.geolite.projects.event\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"projectId\",\"type\":\"string\"},{\"name\":\"projectName\",\"type\":\"string\"},{\"name\":\"location\",\"type\":\"string\"},{\"name\":\"commodity\",\"type\":\"string\"},{\"name\":\"startDate\",\"type\":\"long\"},{\"name\":\"endDate\",\"type\":\"long\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"projectLead\",\"type\":\"string\"},{\"name\":\"createdBy\",\"type\":\"string\"},{\"name\":\"createdDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProjectCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProjectCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProjectCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProjectCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProjectCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProjectCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProjectCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProjectCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProjectCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private long timestamp;
  private java.lang.CharSequence projectId;
  private java.lang.CharSequence projectName;
  private java.lang.CharSequence location;
  private java.lang.CharSequence commodity;
  private long startDate;
  private long endDate;
  private java.lang.CharSequence description;
  private java.lang.CharSequence projectLead;
  private java.lang.CharSequence createdBy;
  private long createdDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProjectCreatedEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param projectId The new value for projectId
   * @param projectName The new value for projectName
   * @param location The new value for location
   * @param commodity The new value for commodity
   * @param startDate The new value for startDate
   * @param endDate The new value for endDate
   * @param description The new value for description
   * @param projectLead The new value for projectLead
   * @param createdBy The new value for createdBy
   * @param createdDate The new value for createdDate
   */
  public ProjectCreatedEvent(java.lang.CharSequence eventId, java.lang.Long timestamp, java.lang.CharSequence projectId, java.lang.CharSequence projectName, java.lang.CharSequence location, java.lang.CharSequence commodity, java.lang.Long startDate, java.lang.Long endDate, java.lang.CharSequence description, java.lang.CharSequence projectLead, java.lang.CharSequence createdBy, java.lang.Long createdDate) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.projectId = projectId;
    this.projectName = projectName;
    this.location = location;
    this.commodity = commodity;
    this.startDate = startDate;
    this.endDate = endDate;
    this.description = description;
    this.projectLead = projectLead;
    this.createdBy = createdBy;
    this.createdDate = createdDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return projectId;
    case 3: return projectName;
    case 4: return location;
    case 5: return commodity;
    case 6: return startDate;
    case 7: return endDate;
    case 8: return description;
    case 9: return projectLead;
    case 10: return createdBy;
    case 11: return createdDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: projectId = (java.lang.CharSequence)value$; break;
    case 3: projectName = (java.lang.CharSequence)value$; break;
    case 4: location = (java.lang.CharSequence)value$; break;
    case 5: commodity = (java.lang.CharSequence)value$; break;
    case 6: startDate = (java.lang.Long)value$; break;
    case 7: endDate = (java.lang.Long)value$; break;
    case 8: description = (java.lang.CharSequence)value$; break;
    case 9: projectLead = (java.lang.CharSequence)value$; break;
    case 10: createdBy = (java.lang.CharSequence)value$; break;
    case 11: createdDate = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'projectId' field.
   * @return The value of the 'projectId' field.
   */
  public java.lang.CharSequence getProjectId() {
    return projectId;
  }


  /**
   * Sets the value of the 'projectId' field.
   * @param value the value to set.
   */
  public void setProjectId(java.lang.CharSequence value) {
    this.projectId = value;
  }

  /**
   * Gets the value of the 'projectName' field.
   * @return The value of the 'projectName' field.
   */
  public java.lang.CharSequence getProjectName() {
    return projectName;
  }


  /**
   * Sets the value of the 'projectName' field.
   * @param value the value to set.
   */
  public void setProjectName(java.lang.CharSequence value) {
    this.projectName = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'commodity' field.
   * @return The value of the 'commodity' field.
   */
  public java.lang.CharSequence getCommodity() {
    return commodity;
  }


  /**
   * Sets the value of the 'commodity' field.
   * @param value the value to set.
   */
  public void setCommodity(java.lang.CharSequence value) {
    this.commodity = value;
  }

  /**
   * Gets the value of the 'startDate' field.
   * @return The value of the 'startDate' field.
   */
  public long getStartDate() {
    return startDate;
  }


  /**
   * Sets the value of the 'startDate' field.
   * @param value the value to set.
   */
  public void setStartDate(long value) {
    this.startDate = value;
  }

  /**
   * Gets the value of the 'endDate' field.
   * @return The value of the 'endDate' field.
   */
  public long getEndDate() {
    return endDate;
  }


  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(long value) {
    this.endDate = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'projectLead' field.
   * @return The value of the 'projectLead' field.
   */
  public java.lang.CharSequence getProjectLead() {
    return projectLead;
  }


  /**
   * Sets the value of the 'projectLead' field.
   * @param value the value to set.
   */
  public void setProjectLead(java.lang.CharSequence value) {
    this.projectLead = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.CharSequence getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.CharSequence value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'createdDate' field.
   * @return The value of the 'createdDate' field.
   */
  public long getCreatedDate() {
    return createdDate;
  }


  /**
   * Sets the value of the 'createdDate' field.
   * @param value the value to set.
   */
  public void setCreatedDate(long value) {
    this.createdDate = value;
  }

  /**
   * Creates a new ProjectCreatedEvent RecordBuilder.
   * @return A new ProjectCreatedEvent RecordBuilder
   */
  public static com.geolite.projects.event.ProjectCreatedEvent.Builder newBuilder() {
    return new com.geolite.projects.event.ProjectCreatedEvent.Builder();
  }

  /**
   * Creates a new ProjectCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProjectCreatedEvent RecordBuilder
   */
  public static com.geolite.projects.event.ProjectCreatedEvent.Builder newBuilder(com.geolite.projects.event.ProjectCreatedEvent.Builder other) {
    if (other == null) {
      return new com.geolite.projects.event.ProjectCreatedEvent.Builder();
    } else {
      return new com.geolite.projects.event.ProjectCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProjectCreatedEvent RecordBuilder by copying an existing ProjectCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProjectCreatedEvent RecordBuilder
   */
  public static com.geolite.projects.event.ProjectCreatedEvent.Builder newBuilder(com.geolite.projects.event.ProjectCreatedEvent other) {
    if (other == null) {
      return new com.geolite.projects.event.ProjectCreatedEvent.Builder();
    } else {
      return new com.geolite.projects.event.ProjectCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProjectCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProjectCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProjectCreatedEvent> {

    private java.lang.CharSequence eventId;
    private long timestamp;
    private java.lang.CharSequence projectId;
    private java.lang.CharSequence projectName;
    private java.lang.CharSequence location;
    private java.lang.CharSequence commodity;
    private long startDate;
    private long endDate;
    private java.lang.CharSequence description;
    private java.lang.CharSequence projectLead;
    private java.lang.CharSequence createdBy;
    private long createdDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.geolite.projects.event.ProjectCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.projectId)) {
        this.projectId = data().deepCopy(fields()[2].schema(), other.projectId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.projectName)) {
        this.projectName = data().deepCopy(fields()[3].schema(), other.projectName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.commodity)) {
        this.commodity = data().deepCopy(fields()[5].schema(), other.commodity);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.startDate)) {
        this.startDate = data().deepCopy(fields()[6].schema(), other.startDate);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.endDate)) {
        this.endDate = data().deepCopy(fields()[7].schema(), other.endDate);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.description)) {
        this.description = data().deepCopy(fields()[8].schema(), other.description);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.projectLead)) {
        this.projectLead = data().deepCopy(fields()[9].schema(), other.projectLead);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[10].schema(), other.createdBy);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[11].schema(), other.createdDate);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing ProjectCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.geolite.projects.event.ProjectCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.projectId)) {
        this.projectId = data().deepCopy(fields()[2].schema(), other.projectId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.projectName)) {
        this.projectName = data().deepCopy(fields()[3].schema(), other.projectName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.location)) {
        this.location = data().deepCopy(fields()[4].schema(), other.location);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.commodity)) {
        this.commodity = data().deepCopy(fields()[5].schema(), other.commodity);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.startDate)) {
        this.startDate = data().deepCopy(fields()[6].schema(), other.startDate);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.endDate)) {
        this.endDate = data().deepCopy(fields()[7].schema(), other.endDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.description)) {
        this.description = data().deepCopy(fields()[8].schema(), other.description);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.projectLead)) {
        this.projectLead = data().deepCopy(fields()[9].schema(), other.projectLead);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[10].schema(), other.createdBy);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[11].schema(), other.createdDate);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProjectId() {
      return projectId;
    }


    /**
      * Sets the value of the 'projectId' field.
      * @param value The value of 'projectId'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setProjectId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.projectId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'projectId' field has been set.
      * @return True if the 'projectId' field has been set, false otherwise.
      */
    public boolean hasProjectId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'projectId' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearProjectId() {
      projectId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProjectName() {
      return projectName;
    }


    /**
      * Sets the value of the 'projectName' field.
      * @param value The value of 'projectName'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setProjectName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.projectName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'projectName' field has been set.
      * @return True if the 'projectName' field has been set, false otherwise.
      */
    public boolean hasProjectName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'projectName' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearProjectName() {
      projectName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.location = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearLocation() {
      location = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'commodity' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommodity() {
      return commodity;
    }


    /**
      * Sets the value of the 'commodity' field.
      * @param value The value of 'commodity'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setCommodity(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.commodity = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'commodity' field has been set.
      * @return True if the 'commodity' field has been set, false otherwise.
      */
    public boolean hasCommodity() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'commodity' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearCommodity() {
      commodity = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'startDate' field.
      * @return The value.
      */
    public long getStartDate() {
      return startDate;
    }


    /**
      * Sets the value of the 'startDate' field.
      * @param value The value of 'startDate'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setStartDate(long value) {
      validate(fields()[6], value);
      this.startDate = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'startDate' field has been set.
      * @return True if the 'startDate' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'startDate' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearStartDate() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDate' field.
      * @return The value.
      */
    public long getEndDate() {
      return endDate;
    }


    /**
      * Sets the value of the 'endDate' field.
      * @param value The value of 'endDate'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setEndDate(long value) {
      validate(fields()[7], value);
      this.endDate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'endDate' field has been set.
      * @return True if the 'endDate' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'endDate' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearEndDate() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.description = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectLead' field.
      * @return The value.
      */
    public java.lang.CharSequence getProjectLead() {
      return projectLead;
    }


    /**
      * Sets the value of the 'projectLead' field.
      * @param value The value of 'projectLead'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setProjectLead(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.projectLead = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'projectLead' field has been set.
      * @return True if the 'projectLead' field has been set, false otherwise.
      */
    public boolean hasProjectLead() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'projectLead' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearProjectLead() {
      projectLead = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setCreatedBy(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.createdBy = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdDate' field.
      * @return The value.
      */
    public long getCreatedDate() {
      return createdDate;
    }


    /**
      * Sets the value of the 'createdDate' field.
      * @param value The value of 'createdDate'.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder setCreatedDate(long value) {
      validate(fields()[11], value);
      this.createdDate = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'createdDate' field has been set.
      * @return True if the 'createdDate' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'createdDate' field.
      * @return This builder.
      */
    public com.geolite.projects.event.ProjectCreatedEvent.Builder clearCreatedDate() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProjectCreatedEvent build() {
      try {
        ProjectCreatedEvent record = new ProjectCreatedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.projectId = fieldSetFlags()[2] ? this.projectId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.projectName = fieldSetFlags()[3] ? this.projectName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.location = fieldSetFlags()[4] ? this.location : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.commodity = fieldSetFlags()[5] ? this.commodity : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.startDate = fieldSetFlags()[6] ? this.startDate : (java.lang.Long) defaultValue(fields()[6]);
        record.endDate = fieldSetFlags()[7] ? this.endDate : (java.lang.Long) defaultValue(fields()[7]);
        record.description = fieldSetFlags()[8] ? this.description : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.projectLead = fieldSetFlags()[9] ? this.projectLead : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.createdBy = fieldSetFlags()[10] ? this.createdBy : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.createdDate = fieldSetFlags()[11] ? this.createdDate : (java.lang.Long) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProjectCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProjectCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProjectCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProjectCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.projectId);

    out.writeString(this.projectName);

    out.writeString(this.location);

    out.writeString(this.commodity);

    out.writeLong(this.startDate);

    out.writeLong(this.endDate);

    out.writeString(this.description);

    out.writeString(this.projectLead);

    out.writeString(this.createdBy);

    out.writeLong(this.createdDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.projectId = in.readString(this.projectId instanceof Utf8 ? (Utf8)this.projectId : null);

      this.projectName = in.readString(this.projectName instanceof Utf8 ? (Utf8)this.projectName : null);

      this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);

      this.commodity = in.readString(this.commodity instanceof Utf8 ? (Utf8)this.commodity : null);

      this.startDate = in.readLong();

      this.endDate = in.readLong();

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.projectLead = in.readString(this.projectLead instanceof Utf8 ? (Utf8)this.projectLead : null);

      this.createdBy = in.readString(this.createdBy instanceof Utf8 ? (Utf8)this.createdBy : null);

      this.createdDate = in.readLong();

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.projectId = in.readString(this.projectId instanceof Utf8 ? (Utf8)this.projectId : null);
          break;

        case 3:
          this.projectName = in.readString(this.projectName instanceof Utf8 ? (Utf8)this.projectName : null);
          break;

        case 4:
          this.location = in.readString(this.location instanceof Utf8 ? (Utf8)this.location : null);
          break;

        case 5:
          this.commodity = in.readString(this.commodity instanceof Utf8 ? (Utf8)this.commodity : null);
          break;

        case 6:
          this.startDate = in.readLong();
          break;

        case 7:
          this.endDate = in.readLong();
          break;

        case 8:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 9:
          this.projectLead = in.readString(this.projectLead instanceof Utf8 ? (Utf8)this.projectLead : null);
          break;

        case 10:
          this.createdBy = in.readString(this.createdBy instanceof Utf8 ? (Utf8)this.createdBy : null);
          break;

        case 11:
          this.createdDate = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










