/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.geolite.scenarios.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ScenarioUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2736006311213866244L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ScenarioUpdatedEvent\",\"namespace\":\"com.geolite.scenarios.event\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"scenarioId\",\"type\":\"string\"},{\"name\":\"scenarioName\",\"type\":\"string\"},{\"name\":\"target\",\"type\":\"string\"},{\"name\":\"methods\",\"type\":\"string\"},{\"name\":\"budget\",\"type\":\"bytes\",\"precision\":10,\"scale\":2},{\"name\":\"modifiedBy\",\"type\":\"string\"},{\"name\":\"modifiedDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ScenarioUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ScenarioUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ScenarioUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ScenarioUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ScenarioUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ScenarioUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ScenarioUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ScenarioUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ScenarioUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private long timestamp;
  private java.lang.CharSequence scenarioId;
  private java.lang.CharSequence scenarioName;
  private java.lang.CharSequence target;
  private java.lang.CharSequence methods;
  private java.nio.ByteBuffer budget;
  private java.lang.CharSequence modifiedBy;
  private long modifiedDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ScenarioUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param scenarioId The new value for scenarioId
   * @param scenarioName The new value for scenarioName
   * @param target The new value for target
   * @param methods The new value for methods
   * @param budget The new value for budget
   * @param modifiedBy The new value for modifiedBy
   * @param modifiedDate The new value for modifiedDate
   */
  public ScenarioUpdatedEvent(java.lang.CharSequence eventId, java.lang.Long timestamp, java.lang.CharSequence scenarioId, java.lang.CharSequence scenarioName, java.lang.CharSequence target, java.lang.CharSequence methods, java.nio.ByteBuffer budget, java.lang.CharSequence modifiedBy, java.lang.Long modifiedDate) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.scenarioId = scenarioId;
    this.scenarioName = scenarioName;
    this.target = target;
    this.methods = methods;
    this.budget = budget;
    this.modifiedBy = modifiedBy;
    this.modifiedDate = modifiedDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return scenarioId;
    case 3: return scenarioName;
    case 4: return target;
    case 5: return methods;
    case 6: return budget;
    case 7: return modifiedBy;
    case 8: return modifiedDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: scenarioId = (java.lang.CharSequence)value$; break;
    case 3: scenarioName = (java.lang.CharSequence)value$; break;
    case 4: target = (java.lang.CharSequence)value$; break;
    case 5: methods = (java.lang.CharSequence)value$; break;
    case 6: budget = (java.nio.ByteBuffer)value$; break;
    case 7: modifiedBy = (java.lang.CharSequence)value$; break;
    case 8: modifiedDate = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'scenarioId' field.
   * @return The value of the 'scenarioId' field.
   */
  public java.lang.CharSequence getScenarioId() {
    return scenarioId;
  }


  /**
   * Sets the value of the 'scenarioId' field.
   * @param value the value to set.
   */
  public void setScenarioId(java.lang.CharSequence value) {
    this.scenarioId = value;
  }

  /**
   * Gets the value of the 'scenarioName' field.
   * @return The value of the 'scenarioName' field.
   */
  public java.lang.CharSequence getScenarioName() {
    return scenarioName;
  }


  /**
   * Sets the value of the 'scenarioName' field.
   * @param value the value to set.
   */
  public void setScenarioName(java.lang.CharSequence value) {
    this.scenarioName = value;
  }

  /**
   * Gets the value of the 'target' field.
   * @return The value of the 'target' field.
   */
  public java.lang.CharSequence getTarget() {
    return target;
  }


  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(java.lang.CharSequence value) {
    this.target = value;
  }

  /**
   * Gets the value of the 'methods' field.
   * @return The value of the 'methods' field.
   */
  public java.lang.CharSequence getMethods() {
    return methods;
  }


  /**
   * Sets the value of the 'methods' field.
   * @param value the value to set.
   */
  public void setMethods(java.lang.CharSequence value) {
    this.methods = value;
  }

  /**
   * Gets the value of the 'budget' field.
   * @return The value of the 'budget' field.
   */
  public java.nio.ByteBuffer getBudget() {
    return budget;
  }


  /**
   * Sets the value of the 'budget' field.
   * @param value the value to set.
   */
  public void setBudget(java.nio.ByteBuffer value) {
    this.budget = value;
  }

  /**
   * Gets the value of the 'modifiedBy' field.
   * @return The value of the 'modifiedBy' field.
   */
  public java.lang.CharSequence getModifiedBy() {
    return modifiedBy;
  }


  /**
   * Sets the value of the 'modifiedBy' field.
   * @param value the value to set.
   */
  public void setModifiedBy(java.lang.CharSequence value) {
    this.modifiedBy = value;
  }

  /**
   * Gets the value of the 'modifiedDate' field.
   * @return The value of the 'modifiedDate' field.
   */
  public long getModifiedDate() {
    return modifiedDate;
  }


  /**
   * Sets the value of the 'modifiedDate' field.
   * @param value the value to set.
   */
  public void setModifiedDate(long value) {
    this.modifiedDate = value;
  }

  /**
   * Creates a new ScenarioUpdatedEvent RecordBuilder.
   * @return A new ScenarioUpdatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder newBuilder() {
    return new com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder();
  }

  /**
   * Creates a new ScenarioUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ScenarioUpdatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder newBuilder(com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder other) {
    if (other == null) {
      return new com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder();
    } else {
      return new com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ScenarioUpdatedEvent RecordBuilder by copying an existing ScenarioUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ScenarioUpdatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder newBuilder(com.geolite.scenarios.event.ScenarioUpdatedEvent other) {
    if (other == null) {
      return new com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder();
    } else {
      return new com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ScenarioUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ScenarioUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<ScenarioUpdatedEvent> {

    private java.lang.CharSequence eventId;
    private long timestamp;
    private java.lang.CharSequence scenarioId;
    private java.lang.CharSequence scenarioName;
    private java.lang.CharSequence target;
    private java.lang.CharSequence methods;
    private java.nio.ByteBuffer budget;
    private java.lang.CharSequence modifiedBy;
    private long modifiedDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.scenarioId)) {
        this.scenarioId = data().deepCopy(fields()[2].schema(), other.scenarioId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.scenarioName)) {
        this.scenarioName = data().deepCopy(fields()[3].schema(), other.scenarioName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.target)) {
        this.target = data().deepCopy(fields()[4].schema(), other.target);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.methods)) {
        this.methods = data().deepCopy(fields()[5].schema(), other.methods);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.budget)) {
        this.budget = data().deepCopy(fields()[6].schema(), other.budget);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.modifiedBy)) {
        this.modifiedBy = data().deepCopy(fields()[7].schema(), other.modifiedBy);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.modifiedDate)) {
        this.modifiedDate = data().deepCopy(fields()[8].schema(), other.modifiedDate);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing ScenarioUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.geolite.scenarios.event.ScenarioUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.scenarioId)) {
        this.scenarioId = data().deepCopy(fields()[2].schema(), other.scenarioId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.scenarioName)) {
        this.scenarioName = data().deepCopy(fields()[3].schema(), other.scenarioName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.target)) {
        this.target = data().deepCopy(fields()[4].schema(), other.target);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.methods)) {
        this.methods = data().deepCopy(fields()[5].schema(), other.methods);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.budget)) {
        this.budget = data().deepCopy(fields()[6].schema(), other.budget);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.modifiedBy)) {
        this.modifiedBy = data().deepCopy(fields()[7].schema(), other.modifiedBy);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.modifiedDate)) {
        this.modifiedDate = data().deepCopy(fields()[8].schema(), other.modifiedDate);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'scenarioId' field.
      * @return The value.
      */
    public java.lang.CharSequence getScenarioId() {
      return scenarioId;
    }


    /**
      * Sets the value of the 'scenarioId' field.
      * @param value The value of 'scenarioId'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setScenarioId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.scenarioId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'scenarioId' field has been set.
      * @return True if the 'scenarioId' field has been set, false otherwise.
      */
    public boolean hasScenarioId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'scenarioId' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearScenarioId() {
      scenarioId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'scenarioName' field.
      * @return The value.
      */
    public java.lang.CharSequence getScenarioName() {
      return scenarioName;
    }


    /**
      * Sets the value of the 'scenarioName' field.
      * @param value The value of 'scenarioName'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setScenarioName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.scenarioName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'scenarioName' field has been set.
      * @return True if the 'scenarioName' field has been set, false otherwise.
      */
    public boolean hasScenarioName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'scenarioName' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearScenarioName() {
      scenarioName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'target' field.
      * @return The value.
      */
    public java.lang.CharSequence getTarget() {
      return target;
    }


    /**
      * Sets the value of the 'target' field.
      * @param value The value of 'target'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setTarget(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.target = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'target' field has been set.
      * @return True if the 'target' field has been set, false otherwise.
      */
    public boolean hasTarget() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'target' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearTarget() {
      target = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'methods' field.
      * @return The value.
      */
    public java.lang.CharSequence getMethods() {
      return methods;
    }


    /**
      * Sets the value of the 'methods' field.
      * @param value The value of 'methods'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setMethods(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.methods = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'methods' field has been set.
      * @return True if the 'methods' field has been set, false otherwise.
      */
    public boolean hasMethods() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'methods' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearMethods() {
      methods = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'budget' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBudget() {
      return budget;
    }


    /**
      * Sets the value of the 'budget' field.
      * @param value The value of 'budget'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setBudget(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.budget = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'budget' field has been set.
      * @return True if the 'budget' field has been set, false otherwise.
      */
    public boolean hasBudget() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'budget' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearBudget() {
      budget = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'modifiedBy' field.
      * @return The value.
      */
    public java.lang.CharSequence getModifiedBy() {
      return modifiedBy;
    }


    /**
      * Sets the value of the 'modifiedBy' field.
      * @param value The value of 'modifiedBy'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setModifiedBy(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.modifiedBy = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'modifiedBy' field has been set.
      * @return True if the 'modifiedBy' field has been set, false otherwise.
      */
    public boolean hasModifiedBy() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'modifiedBy' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearModifiedBy() {
      modifiedBy = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'modifiedDate' field.
      * @return The value.
      */
    public long getModifiedDate() {
      return modifiedDate;
    }


    /**
      * Sets the value of the 'modifiedDate' field.
      * @param value The value of 'modifiedDate'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder setModifiedDate(long value) {
      validate(fields()[8], value);
      this.modifiedDate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'modifiedDate' field has been set.
      * @return True if the 'modifiedDate' field has been set, false otherwise.
      */
    public boolean hasModifiedDate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'modifiedDate' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioUpdatedEvent.Builder clearModifiedDate() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ScenarioUpdatedEvent build() {
      try {
        ScenarioUpdatedEvent record = new ScenarioUpdatedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.scenarioId = fieldSetFlags()[2] ? this.scenarioId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.scenarioName = fieldSetFlags()[3] ? this.scenarioName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.target = fieldSetFlags()[4] ? this.target : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.methods = fieldSetFlags()[5] ? this.methods : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.budget = fieldSetFlags()[6] ? this.budget : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.modifiedBy = fieldSetFlags()[7] ? this.modifiedBy : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.modifiedDate = fieldSetFlags()[8] ? this.modifiedDate : (java.lang.Long) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ScenarioUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ScenarioUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ScenarioUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ScenarioUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.scenarioId);

    out.writeString(this.scenarioName);

    out.writeString(this.target);

    out.writeString(this.methods);

    out.writeBytes(this.budget);

    out.writeString(this.modifiedBy);

    out.writeLong(this.modifiedDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.scenarioId = in.readString(this.scenarioId instanceof Utf8 ? (Utf8)this.scenarioId : null);

      this.scenarioName = in.readString(this.scenarioName instanceof Utf8 ? (Utf8)this.scenarioName : null);

      this.target = in.readString(this.target instanceof Utf8 ? (Utf8)this.target : null);

      this.methods = in.readString(this.methods instanceof Utf8 ? (Utf8)this.methods : null);

      this.budget = in.readBytes(this.budget);

      this.modifiedBy = in.readString(this.modifiedBy instanceof Utf8 ? (Utf8)this.modifiedBy : null);

      this.modifiedDate = in.readLong();

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.scenarioId = in.readString(this.scenarioId instanceof Utf8 ? (Utf8)this.scenarioId : null);
          break;

        case 3:
          this.scenarioName = in.readString(this.scenarioName instanceof Utf8 ? (Utf8)this.scenarioName : null);
          break;

        case 4:
          this.target = in.readString(this.target instanceof Utf8 ? (Utf8)this.target : null);
          break;

        case 5:
          this.methods = in.readString(this.methods instanceof Utf8 ? (Utf8)this.methods : null);
          break;

        case 6:
          this.budget = in.readBytes(this.budget);
          break;

        case 7:
          this.modifiedBy = in.readString(this.modifiedBy instanceof Utf8 ? (Utf8)this.modifiedBy : null);
          break;

        case 8:
          this.modifiedDate = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










