/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.geolite.scenarios.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ScenarioCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1145897026227567368L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ScenarioCreatedEvent\",\"namespace\":\"com.geolite.scenarios.event\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"scenarioId\",\"type\":\"string\"},{\"name\":\"projectId\",\"type\":\"string\"},{\"name\":\"scenarioName\",\"type\":\"string\"},{\"name\":\"target\",\"type\":\"string\"},{\"name\":\"methods\",\"type\":\"string\"},{\"name\":\"budget\",\"type\":\"bytes\",\"precision\":10,\"scale\":2},{\"name\":\"createdBy\",\"type\":\"string\"},{\"name\":\"createdDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ScenarioCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ScenarioCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ScenarioCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ScenarioCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ScenarioCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ScenarioCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ScenarioCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ScenarioCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ScenarioCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private long timestamp;
  private java.lang.CharSequence scenarioId;
  private java.lang.CharSequence projectId;
  private java.lang.CharSequence scenarioName;
  private java.lang.CharSequence target;
  private java.lang.CharSequence methods;
  private java.nio.ByteBuffer budget;
  private java.lang.CharSequence createdBy;
  private long createdDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ScenarioCreatedEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param timestamp The new value for timestamp
   * @param scenarioId The new value for scenarioId
   * @param projectId The new value for projectId
   * @param scenarioName The new value for scenarioName
   * @param target The new value for target
   * @param methods The new value for methods
   * @param budget The new value for budget
   * @param createdBy The new value for createdBy
   * @param createdDate The new value for createdDate
   */
  public ScenarioCreatedEvent(java.lang.CharSequence eventId, java.lang.Long timestamp, java.lang.CharSequence scenarioId, java.lang.CharSequence projectId, java.lang.CharSequence scenarioName, java.lang.CharSequence target, java.lang.CharSequence methods, java.nio.ByteBuffer budget, java.lang.CharSequence createdBy, java.lang.Long createdDate) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.scenarioId = scenarioId;
    this.projectId = projectId;
    this.scenarioName = scenarioName;
    this.target = target;
    this.methods = methods;
    this.budget = budget;
    this.createdBy = createdBy;
    this.createdDate = createdDate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return scenarioId;
    case 3: return projectId;
    case 4: return scenarioName;
    case 5: return target;
    case 6: return methods;
    case 7: return budget;
    case 8: return createdBy;
    case 9: return createdDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: scenarioId = (java.lang.CharSequence)value$; break;
    case 3: projectId = (java.lang.CharSequence)value$; break;
    case 4: scenarioName = (java.lang.CharSequence)value$; break;
    case 5: target = (java.lang.CharSequence)value$; break;
    case 6: methods = (java.lang.CharSequence)value$; break;
    case 7: budget = (java.nio.ByteBuffer)value$; break;
    case 8: createdBy = (java.lang.CharSequence)value$; break;
    case 9: createdDate = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'scenarioId' field.
   * @return The value of the 'scenarioId' field.
   */
  public java.lang.CharSequence getScenarioId() {
    return scenarioId;
  }


  /**
   * Sets the value of the 'scenarioId' field.
   * @param value the value to set.
   */
  public void setScenarioId(java.lang.CharSequence value) {
    this.scenarioId = value;
  }

  /**
   * Gets the value of the 'projectId' field.
   * @return The value of the 'projectId' field.
   */
  public java.lang.CharSequence getProjectId() {
    return projectId;
  }


  /**
   * Sets the value of the 'projectId' field.
   * @param value the value to set.
   */
  public void setProjectId(java.lang.CharSequence value) {
    this.projectId = value;
  }

  /**
   * Gets the value of the 'scenarioName' field.
   * @return The value of the 'scenarioName' field.
   */
  public java.lang.CharSequence getScenarioName() {
    return scenarioName;
  }


  /**
   * Sets the value of the 'scenarioName' field.
   * @param value the value to set.
   */
  public void setScenarioName(java.lang.CharSequence value) {
    this.scenarioName = value;
  }

  /**
   * Gets the value of the 'target' field.
   * @return The value of the 'target' field.
   */
  public java.lang.CharSequence getTarget() {
    return target;
  }


  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(java.lang.CharSequence value) {
    this.target = value;
  }

  /**
   * Gets the value of the 'methods' field.
   * @return The value of the 'methods' field.
   */
  public java.lang.CharSequence getMethods() {
    return methods;
  }


  /**
   * Sets the value of the 'methods' field.
   * @param value the value to set.
   */
  public void setMethods(java.lang.CharSequence value) {
    this.methods = value;
  }

  /**
   * Gets the value of the 'budget' field.
   * @return The value of the 'budget' field.
   */
  public java.nio.ByteBuffer getBudget() {
    return budget;
  }


  /**
   * Sets the value of the 'budget' field.
   * @param value the value to set.
   */
  public void setBudget(java.nio.ByteBuffer value) {
    this.budget = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.CharSequence getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.CharSequence value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'createdDate' field.
   * @return The value of the 'createdDate' field.
   */
  public long getCreatedDate() {
    return createdDate;
  }


  /**
   * Sets the value of the 'createdDate' field.
   * @param value the value to set.
   */
  public void setCreatedDate(long value) {
    this.createdDate = value;
  }

  /**
   * Creates a new ScenarioCreatedEvent RecordBuilder.
   * @return A new ScenarioCreatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioCreatedEvent.Builder newBuilder() {
    return new com.geolite.scenarios.event.ScenarioCreatedEvent.Builder();
  }

  /**
   * Creates a new ScenarioCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ScenarioCreatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioCreatedEvent.Builder newBuilder(com.geolite.scenarios.event.ScenarioCreatedEvent.Builder other) {
    if (other == null) {
      return new com.geolite.scenarios.event.ScenarioCreatedEvent.Builder();
    } else {
      return new com.geolite.scenarios.event.ScenarioCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ScenarioCreatedEvent RecordBuilder by copying an existing ScenarioCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ScenarioCreatedEvent RecordBuilder
   */
  public static com.geolite.scenarios.event.ScenarioCreatedEvent.Builder newBuilder(com.geolite.scenarios.event.ScenarioCreatedEvent other) {
    if (other == null) {
      return new com.geolite.scenarios.event.ScenarioCreatedEvent.Builder();
    } else {
      return new com.geolite.scenarios.event.ScenarioCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ScenarioCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ScenarioCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ScenarioCreatedEvent> {

    private java.lang.CharSequence eventId;
    private long timestamp;
    private java.lang.CharSequence scenarioId;
    private java.lang.CharSequence projectId;
    private java.lang.CharSequence scenarioName;
    private java.lang.CharSequence target;
    private java.lang.CharSequence methods;
    private java.nio.ByteBuffer budget;
    private java.lang.CharSequence createdBy;
    private long createdDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.geolite.scenarios.event.ScenarioCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.scenarioId)) {
        this.scenarioId = data().deepCopy(fields()[2].schema(), other.scenarioId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.projectId)) {
        this.projectId = data().deepCopy(fields()[3].schema(), other.projectId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.scenarioName)) {
        this.scenarioName = data().deepCopy(fields()[4].schema(), other.scenarioName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.target)) {
        this.target = data().deepCopy(fields()[5].schema(), other.target);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.methods)) {
        this.methods = data().deepCopy(fields()[6].schema(), other.methods);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.budget)) {
        this.budget = data().deepCopy(fields()[7].schema(), other.budget);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[8].schema(), other.createdBy);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[9].schema(), other.createdDate);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing ScenarioCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.geolite.scenarios.event.ScenarioCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.scenarioId)) {
        this.scenarioId = data().deepCopy(fields()[2].schema(), other.scenarioId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.projectId)) {
        this.projectId = data().deepCopy(fields()[3].schema(), other.projectId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.scenarioName)) {
        this.scenarioName = data().deepCopy(fields()[4].schema(), other.scenarioName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.target)) {
        this.target = data().deepCopy(fields()[5].schema(), other.target);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.methods)) {
        this.methods = data().deepCopy(fields()[6].schema(), other.methods);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.budget)) {
        this.budget = data().deepCopy(fields()[7].schema(), other.budget);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[8].schema(), other.createdBy);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[9].schema(), other.createdDate);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'scenarioId' field.
      * @return The value.
      */
    public java.lang.CharSequence getScenarioId() {
      return scenarioId;
    }


    /**
      * Sets the value of the 'scenarioId' field.
      * @param value The value of 'scenarioId'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setScenarioId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.scenarioId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'scenarioId' field has been set.
      * @return True if the 'scenarioId' field has been set, false otherwise.
      */
    public boolean hasScenarioId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'scenarioId' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearScenarioId() {
      scenarioId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'projectId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProjectId() {
      return projectId;
    }


    /**
      * Sets the value of the 'projectId' field.
      * @param value The value of 'projectId'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setProjectId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.projectId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'projectId' field has been set.
      * @return True if the 'projectId' field has been set, false otherwise.
      */
    public boolean hasProjectId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'projectId' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearProjectId() {
      projectId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'scenarioName' field.
      * @return The value.
      */
    public java.lang.CharSequence getScenarioName() {
      return scenarioName;
    }


    /**
      * Sets the value of the 'scenarioName' field.
      * @param value The value of 'scenarioName'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setScenarioName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.scenarioName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'scenarioName' field has been set.
      * @return True if the 'scenarioName' field has been set, false otherwise.
      */
    public boolean hasScenarioName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'scenarioName' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearScenarioName() {
      scenarioName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'target' field.
      * @return The value.
      */
    public java.lang.CharSequence getTarget() {
      return target;
    }


    /**
      * Sets the value of the 'target' field.
      * @param value The value of 'target'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setTarget(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.target = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'target' field has been set.
      * @return True if the 'target' field has been set, false otherwise.
      */
    public boolean hasTarget() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'target' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearTarget() {
      target = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'methods' field.
      * @return The value.
      */
    public java.lang.CharSequence getMethods() {
      return methods;
    }


    /**
      * Sets the value of the 'methods' field.
      * @param value The value of 'methods'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setMethods(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.methods = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'methods' field has been set.
      * @return True if the 'methods' field has been set, false otherwise.
      */
    public boolean hasMethods() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'methods' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearMethods() {
      methods = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'budget' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getBudget() {
      return budget;
    }


    /**
      * Sets the value of the 'budget' field.
      * @param value The value of 'budget'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setBudget(java.nio.ByteBuffer value) {
      validate(fields()[7], value);
      this.budget = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'budget' field has been set.
      * @return True if the 'budget' field has been set, false otherwise.
      */
    public boolean hasBudget() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'budget' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearBudget() {
      budget = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setCreatedBy(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.createdBy = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdDate' field.
      * @return The value.
      */
    public long getCreatedDate() {
      return createdDate;
    }


    /**
      * Sets the value of the 'createdDate' field.
      * @param value The value of 'createdDate'.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder setCreatedDate(long value) {
      validate(fields()[9], value);
      this.createdDate = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'createdDate' field has been set.
      * @return True if the 'createdDate' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'createdDate' field.
      * @return This builder.
      */
    public com.geolite.scenarios.event.ScenarioCreatedEvent.Builder clearCreatedDate() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ScenarioCreatedEvent build() {
      try {
        ScenarioCreatedEvent record = new ScenarioCreatedEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.scenarioId = fieldSetFlags()[2] ? this.scenarioId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.projectId = fieldSetFlags()[3] ? this.projectId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.scenarioName = fieldSetFlags()[4] ? this.scenarioName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.target = fieldSetFlags()[5] ? this.target : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.methods = fieldSetFlags()[6] ? this.methods : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.budget = fieldSetFlags()[7] ? this.budget : (java.nio.ByteBuffer) defaultValue(fields()[7]);
        record.createdBy = fieldSetFlags()[8] ? this.createdBy : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.createdDate = fieldSetFlags()[9] ? this.createdDate : (java.lang.Long) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ScenarioCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ScenarioCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ScenarioCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ScenarioCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.scenarioId);

    out.writeString(this.projectId);

    out.writeString(this.scenarioName);

    out.writeString(this.target);

    out.writeString(this.methods);

    out.writeBytes(this.budget);

    out.writeString(this.createdBy);

    out.writeLong(this.createdDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.scenarioId = in.readString(this.scenarioId instanceof Utf8 ? (Utf8)this.scenarioId : null);

      this.projectId = in.readString(this.projectId instanceof Utf8 ? (Utf8)this.projectId : null);

      this.scenarioName = in.readString(this.scenarioName instanceof Utf8 ? (Utf8)this.scenarioName : null);

      this.target = in.readString(this.target instanceof Utf8 ? (Utf8)this.target : null);

      this.methods = in.readString(this.methods instanceof Utf8 ? (Utf8)this.methods : null);

      this.budget = in.readBytes(this.budget);

      this.createdBy = in.readString(this.createdBy instanceof Utf8 ? (Utf8)this.createdBy : null);

      this.createdDate = in.readLong();

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.scenarioId = in.readString(this.scenarioId instanceof Utf8 ? (Utf8)this.scenarioId : null);
          break;

        case 3:
          this.projectId = in.readString(this.projectId instanceof Utf8 ? (Utf8)this.projectId : null);
          break;

        case 4:
          this.scenarioName = in.readString(this.scenarioName instanceof Utf8 ? (Utf8)this.scenarioName : null);
          break;

        case 5:
          this.target = in.readString(this.target instanceof Utf8 ? (Utf8)this.target : null);
          break;

        case 6:
          this.methods = in.readString(this.methods instanceof Utf8 ? (Utf8)this.methods : null);
          break;

        case 7:
          this.budget = in.readBytes(this.budget);
          break;

        case 8:
          this.createdBy = in.readString(this.createdBy instanceof Utf8 ? (Utf8)this.createdBy : null);
          break;

        case 9:
          this.createdDate = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










